// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/callsheets" | "/app/checklists" | "/app/checklists/[id]" | "/app/checklists/new" | "/app/clients" | "/app/crm" | "/app/dashboard" | "/app/diagnostics" | "/app/inbox" | "/app/insights" | "/app/journal" | "/app/logistics" | "/app/preferences" | "/app/projects" | "/app/projects/[id]" | "/app/projects/new" | "/app/rates" | "/app/settings" | "/app/tasks" | "/app/templates" | "/app/weather" | "/auth/auth-code-error" | "/auth/set-session" | "/login" | "/portal" | "/portal/invite" | "/portal/login" | "/portal/projects/[id]" | "/portal/review/[deliverableId]" | "/reset-password" | "/review-link/[token]"
type AppRouteHandlerRoutes = "/api/admin/bootstrap" | "/api/admin/create-user" | "/api/admin/invite" | "/api/admin/org-role" | "/api/auth/validate-audience" | "/api/calendar/event.ics" | "/api/calendar/feed.ics" | "/api/callsheets" | "/api/catalog" | "/api/clients/invites" | "/api/clients/invites/accept" | "/api/conversations" | "/api/conversations/[id]" | "/api/conversations/[id]/messages" | "/api/conversations/[id]/read" | "/api/conversations/[id]/suggest" | "/api/crm" | "/api/crm/deals" | "/api/crm/import" | "/api/dropbox/ai-tag" | "/api/dropbox/callback" | "/api/dropbox/connect" | "/api/dropbox/files" | "/api/dropbox/sync" | "/api/export/pptx" | "/api/geo/geocode" | "/api/geo/route" | "/api/insights/cleanup" | "/api/insights/recalculate" | "/api/journal" | "/api/journal/summarize" | "/api/logistics" | "/api/messages" | "/api/messages/read" | "/api/notifications" | "/api/notifications/dispatch" | "/api/plugins/fuel" | "/api/plugins/route" | "/api/plugins/weather" | "/api/portal/milestones" | "/api/portal/requests" | "/api/portal/suggest-reply" | "/api/projects" | "/api/review-link/[token]" | "/api/review-link/[token]/comments" | "/api/review/approvals" | "/api/review/comments" | "/api/review/deliverables/[deliverableId]" | "/api/review/links" | "/api/review/tasks" | "/api/review/threads" | "/api/review/threads/[threadId]" | "/api/tasks" | "/api/tasks/from-text" | "/api/weather" | "/api/weather/forecast" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/app" | "/portal"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/bootstrap": {}
  "/api/admin/create-user": {}
  "/api/admin/invite": {}
  "/api/admin/org-role": {}
  "/api/auth/validate-audience": {}
  "/api/calendar/event.ics": {}
  "/api/calendar/feed.ics": {}
  "/api/callsheets": {}
  "/api/catalog": {}
  "/api/clients/invites": {}
  "/api/clients/invites/accept": {}
  "/api/conversations": {}
  "/api/conversations/[id]": { "id": string; }
  "/api/conversations/[id]/messages": { "id": string; }
  "/api/conversations/[id]/read": { "id": string; }
  "/api/conversations/[id]/suggest": { "id": string; }
  "/api/crm": {}
  "/api/crm/deals": {}
  "/api/crm/import": {}
  "/api/dropbox/ai-tag": {}
  "/api/dropbox/callback": {}
  "/api/dropbox/connect": {}
  "/api/dropbox/files": {}
  "/api/dropbox/sync": {}
  "/api/export/pptx": {}
  "/api/geo/geocode": {}
  "/api/geo/route": {}
  "/api/insights/cleanup": {}
  "/api/insights/recalculate": {}
  "/api/journal": {}
  "/api/journal/summarize": {}
  "/api/logistics": {}
  "/api/messages": {}
  "/api/messages/read": {}
  "/api/notifications": {}
  "/api/notifications/dispatch": {}
  "/api/plugins/fuel": {}
  "/api/plugins/route": {}
  "/api/plugins/weather": {}
  "/api/portal/milestones": {}
  "/api/portal/requests": {}
  "/api/portal/suggest-reply": {}
  "/api/projects": {}
  "/api/review-link/[token]": { "token": string; }
  "/api/review-link/[token]/comments": { "token": string; }
  "/api/review/approvals": {}
  "/api/review/comments": {}
  "/api/review/deliverables/[deliverableId]": { "deliverableId": string; }
  "/api/review/links": {}
  "/api/review/tasks": {}
  "/api/review/threads": {}
  "/api/review/threads/[threadId]": { "threadId": string; }
  "/api/tasks": {}
  "/api/tasks/from-text": {}
  "/api/weather": {}
  "/api/weather/forecast": {}
  "/app": {}
  "/app/callsheets": {}
  "/app/checklists": {}
  "/app/checklists/[id]": { "id": string; }
  "/app/checklists/new": {}
  "/app/clients": {}
  "/app/crm": {}
  "/app/dashboard": {}
  "/app/diagnostics": {}
  "/app/inbox": {}
  "/app/insights": {}
  "/app/journal": {}
  "/app/logistics": {}
  "/app/preferences": {}
  "/app/projects": {}
  "/app/projects/[id]": { "id": string; }
  "/app/projects/new": {}
  "/app/rates": {}
  "/app/settings": {}
  "/app/tasks": {}
  "/app/templates": {}
  "/app/weather": {}
  "/auth/auth-code-error": {}
  "/auth/callback": {}
  "/auth/set-session": {}
  "/login": {}
  "/portal": {}
  "/portal/invite": {}
  "/portal/login": {}
  "/portal/projects/[id]": { "id": string; }
  "/portal/review/[deliverableId]": { "deliverableId": string; }
  "/reset-password": {}
  "/review-link/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
  "/portal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
