// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/app/callsheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/callsheets">> = Specific
  const handler = {} as typeof import("../../src/app/app/callsheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/checklists/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/checklists/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/app/checklists/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/checklists/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/checklists/new">> = Specific
  const handler = {} as typeof import("../../src/app/app/checklists/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/checklists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/checklists">> = Specific
  const handler = {} as typeof import("../../src/app/app/checklists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/clients">> = Specific
  const handler = {} as typeof import("../../src/app/app/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/crm">> = Specific
  const handler = {} as typeof import("../../src/app/app/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/diagnostics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/diagnostics">> = Specific
  const handler = {} as typeof import("../../src/app/app/diagnostics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/app/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/insights">> = Specific
  const handler = {} as typeof import("../../src/app/app/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/journal">> = Specific
  const handler = {} as typeof import("../../src/app/app/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/logistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logistics">> = Specific
  const handler = {} as typeof import("../../src/app/app/logistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/app/preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/new">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/rates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/rates">> = Specific
  const handler = {} as typeof import("../../src/app/app/rates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../src/app/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/app/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/templates">> = Specific
  const handler = {} as typeof import("../../src/app/app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/weather/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/weather">> = Specific
  const handler = {} as typeof import("../../src/app/app/weather/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/auth-code-error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/auth-code-error">> = Specific
  const handler = {} as typeof import("../../src/app/auth/auth-code-error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/set-session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/set-session">> = Specific
  const handler = {} as typeof import("../../src/app/auth/set-session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/invite">> = Specific
  const handler = {} as typeof import("../../src/app/portal/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/login">> = Specific
  const handler = {} as typeof import("../../src/app/portal/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../src/app/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/review/[deliverableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/review/[deliverableId]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/review/[deliverableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/review-link/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review-link/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/review-link/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bootstrap">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/create-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/create-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/org-role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/org-role">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/org-role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/validate-audience/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/validate-audience">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/validate-audience/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/event.ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/event.ics">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/event.ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/feed.ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/feed.ics">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/feed.ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/callsheets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/callsheets">> = Specific
  const handler = {} as typeof import("../../src/app/api/callsheets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/invites/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/invites/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/invites/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/invites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/invites">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/invites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/[id]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/[id]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]/read">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/[id]/suggest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]/suggest">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/[id]/suggest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/deals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/deals">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/deals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/crm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm">> = Specific
  const handler = {} as typeof import("../../src/app/api/crm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dropbox/ai-tag/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dropbox/ai-tag">> = Specific
  const handler = {} as typeof import("../../src/app/api/dropbox/ai-tag/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dropbox/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dropbox/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/dropbox/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dropbox/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dropbox/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/dropbox/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dropbox/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dropbox/files">> = Specific
  const handler = {} as typeof import("../../src/app/api/dropbox/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dropbox/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dropbox/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/dropbox/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/pptx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/pptx">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/pptx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo/geocode">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo/route/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo/route">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo/route/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights/cleanup">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/recalculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights/recalculate">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/recalculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/journal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journal">> = Specific
  const handler = {} as typeof import("../../src/app/api/journal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/journal/summarize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journal/summarize">> = Specific
  const handler = {} as typeof import("../../src/app/api/journal/summarize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/logistics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logistics">> = Specific
  const handler = {} as typeof import("../../src/app/api/logistics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/read">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plugins/fuel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugins/fuel">> = Specific
  const handler = {} as typeof import("../../src/app/api/plugins/fuel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plugins/route/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugins/route">> = Specific
  const handler = {} as typeof import("../../src/app/api/plugins/route/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plugins/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugins/weather">> = Specific
  const handler = {} as typeof import("../../src/app/api/plugins/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/milestones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/milestones">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/milestones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/suggest-reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/suggest-reply">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/suggest-reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review-link/[token]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review-link/[token]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/review-link/[token]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review-link/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review-link/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/api/review-link/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/approvals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/approvals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/deliverables/[deliverableId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/deliverables/[deliverableId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/deliverables/[deliverableId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/links">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/threads/[threadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/threads/[threadId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/threads/[threadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/threads">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/from-text/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/from-text">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/from-text/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weather/forecast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather/forecast">> = Specific
  const handler = {} as typeof import("../../src/app/api/weather/forecast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather">> = Specific
  const handler = {} as typeof import("../../src/app/api/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../src/app/portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
